version: '3.7'

services:

  db:
    container_name: postgres_db23333
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - ./.env

  web:
    container_name: django_web23333
    restart: unless-stopped
    build:
      context: .
    volumes:
      - static/:/static
      - media/:/media
      - ./:/app
    entrypoint: ./wsgi-entrypoint.sh
    ports:
      - 8003:8003
    networks:
      - my-network
    depends_on:
      - db


volumes:
  postgres_data:
  media:
  static:

networks:
  my-network: